export { default as FacebookIcon } from "./Facebook"
export { default as TwitterIcon } from "./Twitter"
export { default as InstagramIcon } from "./Instagram"
export { default as LinkedInIcon } from "./LinkedIn"
export { default as UserIcon } from "./User"
export { default as HeartIcon } from "./Heart"
export { default as SolidHeartIcon } from "./SolidHeart"
export { default as StarIcon } from "./Star"
export { default as TrashIcon } from "./Trash"
export { default as AddressBookIcon } from "./AddressBook"
export { default as IdCardIcon } from "./IdCard"
export { default as PackageIcon } from "./Package"
export { default as FeedBackIcon } from "./FeedBack"
export { default as LocationIcon } from "./Location"
export { default as ClipboarIcon } from "./Clipboard"
export { default as NoteBookIcon } from "./NoteBook"
export { default as NotePadIcon } from "./NotePad"
export { default as LogoutIcon } from "./Logout"
export { default as DeleteIcon } from "./Delete"
export { default as EditIcon } from "./Edit"
export { default as GuaranteeIcon } from "./Guarantee"
export { default as TickIcon } from "./Tick"
export * from './Email'
export * from './Search'
