import React from "react"
import type { AppProps } from "next/app"
import { wrapper } from "store"
import axios from "axios"
import { connect } from "react-redux"
import '../styles/default/main.css'
import { RecoilRoot } from "recoil";
import { DebugObserver } from "components/DebugObserver";
import { onClientStart } from "utils/client"
import Head from 'next/head'
import 'antd/dist/antd.css'

axios.defaults.baseURL = process.env.NEXT_PUBLIC_API_HOST
axios.defaults.timeout = 30000
onClientStart()

const App = ({ Component, pageProps }: AppProps) => {
  return (
    <RecoilRoot>
      <Head>
        <meta property="l13e:version" content={process.env.NEXT_PUBLIC_VERSION} key="version" />
        <title>VNT</title>
        <link rel="shortcut icon" href="/favicons/VNT_50x50.png" />
        <meta
          name='description'
          content='Generated by create next app'
        />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <DebugObserver />
      <Component {...pageProps} />
    </RecoilRoot>
  )
}

const mapState = () => ({
  // publicKeys: publicKeysSelector(state)
})

const ConnectedApp = connect(mapState)(App)
export default wrapper.withRedux(ConnectedApp)